understanding JS call apply and bind and how they are different
loverajoel/jstips pull request #403
Opened 2017-03-29 20:39 UTC by sagarmunjal

## Call apply and bind
[@munjalsagar](https://twitter.com/munjalsagar)

2017-04-06 13:28 UTC, zenopopovici commented
There are a lot of language issues ... we can't merge it like this.

2017-04-06 13:30 UTC, sagarmunjal commented
What language issues? Could u elaborate?
On Thu, 6 Apr 2017 at 6:58 PM, Zeno Popovici <notifications@github.com>
wrote:

> There are a lot of language issues ... we can't merge it like this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/loverajoel/jstips/pull/403#issuecomment-292174469>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AITj-ueHR91ONEdCymRKz6BAczx0IaFTks5rtOiSgaJpZM4Mthni>
> .
>

2017-04-06 13:33 UTC, zenopopovici requested changes

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +title: Call apply and bind. and how they are different.
Title is weird, maybe "JS Apply, Call, and Bind Methods"

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +You have three automobiles `your_scooter , your_car and your_jet` which start with the same mechanism (method).
automobiles => vehicles

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +    	    push_button_engineStart: function (runtime){
Either camelcase or _

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +If you run the following lines of code, they will give an error. WHY?
give => throw

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +Lets understand when is call and apply used. Lets suppose that you are an engineer and you have `your_scooter`, `your_car` and `your_jet` which did not come with a push_button_engine_start and you wi
Let's

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +    //your_scooter.push_button_engineStart();
Space after comment

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +Further we use apply or call using the dot notation.
Further doesn't apply here.

2017-04-06 13:33 UTC, zenopopovici commented on _posts/en/javascript/2017-03-29-understanding-apply-call-bind.md
> +**what is JS Bind function?**
Start sentence with uppercase.

2017-04-06 13:33 UTC, zenopopovici commented
There are a lot more. I can't re-write the tip for you. Please get someone to spellcheck it.

2017-04-06 13:54 UTC, sagarmunjal commented
I'll make note of the spell check and language and rectify.

Is there anything amiss in the logic explained how apply call and bind
work?


On Thu, 6 Apr 2017 at 7:03 PM, Zeno Popovici <notifications@github.com>
wrote:

> There are a lot more. I can't re-write the tip for you. Please get someone
> to spellcheck it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/loverajoel/jstips/pull/403#issuecomment-292175810>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AITj-p_8iLWGbDxspwC0dSyQixT9QYZzks5rtOm-gaJpZM4Mthni>
> .
>

2017-04-06 13:58 UTC, zenopopovici commented
That's for the other members to weigh in. I personally think in can be improved. See: https://alexperry.io/personal/2016/04/03/How-to-use-apply-bind-and-call.html

2017-05-31 16:35 UTC, zenopopovici approved these changes

2017-05-31 16:36 UTC, zenopopovici reviewed
The title is still not correct.

2021-12-06 17:11 UTC, closed without merging

2021-12-06 17:11 UTC, zenopopovici commented
Quality issues